server:
  port: 3000

database:
  dialect: ${DATABASE_DIALECT}
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  database: ${DATABASE_NAME}
  
security:
  secret: ${SECRET}