version: '3.8'

services:
  postgres:
    container_name: container_postgres
    image: postgres:13
    restart: always
    environment:
     - POSTGRES_DB=customers
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: customer-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_DIALECT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: customers
    depends_on:
      - postgres

volumes:
  postgres-data: